compiler_command = "./tools/gcc_2.7.2/gcc -B ./tools/gcc_2.7.2/ -O1 -G0 -mips3 -mgp32 -mfp32 -Wa,-Iinclude -D_LANGUAGE_C -D_MIPS_SZLONG=32 -D_MIPS_SZINT=32 -D_FINALROM -DSUPPORT_NAUDIO -DF3DEX_GBI_2 -g2 -I. -I include -I src -c"
assembler_command = "mips-linux-gnu-as -G 0 -Iinclude -mips3 -mabi=32"

compiler_type = "gcc"

[decompme.compilers]
"tools/gcc_2.7.2/linux/gcc" = "gcc2.7.2"